### ISSUE TITLE
code review

### ISSUE THREAD

**Issue by lacolaco** [aziz819/Httpwebpage#7]
### mainメソッド

- try-catchの範囲が広い。tryブロックではできるだけ最低限のメソッド呼び出しだけを行なったほうが、どの処理が原因で例外が発生するのかを視覚的に判断しやすい

```
    public static void main(String[] args){
        try {
            Server server = new Server(); // これはtryの外でも良いよね
            server.portNumSet(); // これは IOExceptionを吐くからここじゃないといけない
            server.startServer(); // これはserver.portNumSet();が成功しないと呼べないからここになりそう
        } catch (IOException e) {
            System.out.println("ServerSocketのインスタンス作成時にエラー発生しました:" + e.getMessage());
            e.printStackTrace();
        }
    }
```

だけど、もっというと`portNumSet()`と`startServer()`を分ける意味ってなんだろうと考えたら、`startServer()`だけでよさそう。さらに言えば、`startServer()`を`startServer(SERVER_PORT)`にすると `任意のポート番号でソケットを生成する` メソッドとして扱いやすくなる

呼び出しのイメージはこんな感じ

```
    public static void main(String[] args){
        Server server = new Server();
        try {
            server.startServer(SERVER_PORT);
        } catch (IOException e) {
            System.out.println("サーバーの開始に失敗しました:" + e.getMessage());
            e.printStackTrace();
        }
    }
```

最初のコードとどちらが読みやすくてシンプルかを見比べてみてください

### startServer()

- ConnectionHandlerのインスタンスを生成するとクライアントにレスポンスが返されるのはコンストラクタの責務としておかしい

この部分

```
           try {
                client = serverSocket.accept();
                InputStream is = client.getInputStream();
                OutputStream os = client.getOutputStream();
                handler = new ConnectionHandler(is, os);
                client.close();
            }
```

1行ずつ日本語に翻訳してみると

1. サーバーへの接続要求を受け入れて、クライアントのソケットを取得する
2. クライアントからのリクエストが書き込まれるStreamを取得する
3. クライアントへのレスポンスを書き込むStreamを取得する
4. ConnectionHandlerのインスタンスを生成する
5. クライアントとの接続を終了する

となって、4番目で急展開が起きています。その証拠として、`handler`変数は宣言されて代入されてますが、その後何も使われずに破棄されています。
コンストラクタは`new`でインスタンス化したときに必ず呼ばれるメソッドですが、これは**インスタンスの初期化のため**に使われるもので、何か副作用を起こす処理を行うべきではありません。この場合インスタンスを作っただけで自動的にOutputStreamに書き込まれるのでテストも難しいです。

わかりやすい段取りを考えれば、

1. サーバーへの接続要求を受け入れて、クライアントのソケットを取得する
2. クライアントからのリクエストが書き込まれるStreamを取得する
3. クライアントへのレスポンスを書き込むStreamを取得する
4. ConnectionHandlerのインスタンスを生成する
5. レスポンスをOutputStreamに書き込む
6. クライアントとの接続を終了する

となるほうがよいはずです。実装イメージとしては次のようになるとわかりやすいでしょう。

```
           try {
                client = serverSocket.accept();
                InputStream is = client.getInputStream();
                OutputStream os = client.getOutputStream();
                ConnectionHandler handler = new ConnectionHandler(is, os);
                handler.writeResponse();
                client.close();
            }
```

## ConnectionHandler.java

- コンストラクタに処理を詰め込まない

先述のとおり。各メソッドには責務があり、コンストラクタも**インスタンスを組み立てる(construction)する**という責務を持ったひとつのメソッドです。今のコンストラクタは インスタンスを初期化する / リクエストを読み込む / レスポンスを書き込む まですべてやっているので、外部への影響がある「レスポンスの書き込み」は最低限メソッドとして切り出してコンストラクタから外しましょう

- try文が長すぎる

先述のとおり、1つのtry文が長いと、どのタイミングでcatch句に飛ぶのか読み取りづらくなるので、リクエストのパースと、ファイルの存在チェックで分けたほうがよいです

## HttpRequest.java

- 名前
  - `QUANTYTI`ではなく QUANTITYでは？
  - あとこういう場合、QuantityよりもSizeのほうがよく使われます
  - 意味なく短縮しないようにしましょう `private BufferedReader buffr;` -> `bufferedReader;`

- `postParametersMap`と`getParametersMap`
  - GETとPOSTでクエリパラメータの仕様が違う？これは統合できるのでは？
  - 読み取る元の場所が違うだけで、パースの処理は変わらないようにみえるので、まとめられないかやってみましょう

## FileResources.java

- コードフォーマット
  - インデントを揃えましょう
- コードスタイルの統一
  - `url`と書いたり `this.url` と書いたりのブレを無くしましょう
- 名前
  - `getContenType` -> `getContentType`
- コンストラクタの責務
  - URIからtypeを抜き出して保存しておく必要はありますか？`getContentType`メソッドが呼び出されたときにできるのでは？
  - あと、 `html` や `htm` といった文字列はcontentTypeではなくただのファイル拡張子です
- getContentType
  - あるファイルのContent-Typeが、ステータスコードによって左右されるというのはおかしくないですか？
  - FileResourcesという責務の範囲で、やるべきこと、やるべきじゃないことを考えてみましょう

## HttpResponse.java

- コンストラクタの責務

このクラスも、インスタンスが作られると自動的にすべての処理が行われて、インスタンス自体には意味がなくなっています。証拠に、呼び出し側では宣言したインスタンスは何も使われずに破棄されています

```
       try {

            response = new HttpResponse(statusCode, os, fileresources, statusline);

        }
```

コンストラクタは初期化、レスポンスの書き込みは別メソッドにしましょう。

- コードフォーマット
  - インデントを揃えましょう
- コードスタイル
  - `bfr` みたいな短縮名はなるべく避けましょう
  - `BufferedReader bfr = new BufferedReader(new InputStreamReader(new FileInputStream(fileresources)));` は、ちゃんと意味をもった名前にすれば最低でも `fileContentReader` くらいの名前になるはずです。型は宣言元を見れば分かるのでその変数が何なのかをちゃんと変数名で説明しましょう
  - `fileIn`も同じく

### getStatusCode

- `getStatusCode` は、実際に返しているのは「ステータスコードの行」です。 `getStatusCodeLine` のほうが正しいでしょう
- StringBuilderを返すのが本当に正しいかを考えましょう。1行を返すならStringでいいはずです。
  - StringBuilderを生成するのはHttpResponseの仕事ではないですか？

### IncorrectStatusCode
- 名前が変ですね
  - メソッドは原則として動詞です。このメソッドがやっていること、返すものをちゃんと説明する名前にしましょう
  - そもそもcamelCaseになってないですね

**Comment by aziz819** [comment]
#StatusLine.java
----------------------------------------------------------------------------------------------------
##getStatusCode

StringBuilderを返すのが本当に正しいかを考えましょう。1行を返すならStringでいいはずです。
StringBuilderを生成するのはHttpResponseの仕事ではないですか？


**その一行をStringで返すのを考えてみましたが、ステータスコードが整数型なのでそれをレスポンスラインのステータスコードにセットしてStringBuilderでその一行を組んで返しましたが、**

**Comment by aziz819** [comment]
getStatusCode

StringBuilderを返すのが本当に正しいかを考えましょう。1行を返すならStringでいいはずです。
StringBuilderを生成するのはHttpResponseの仕事ではないですか？

*****

- **その一行をStringで返すのを考えてみましたが、ステータスコードが整数型なのでそれをレスポンスラインのステータスコードにセットしてStringBuilderでその一行を組んで返しましたが**

**Comment by lacolaco** [comment]
## Server.java
### startServerメソッド

- メソッドの仮引数名がアッパーケースなのはよくないです。 `serverPort` でよいでしょう
- `ConnectionHandler`について指摘した内容が改善されてません。newでインスタンスを生成した戻り値を使わないケースはまずありえません

## ConnectionHandler.java

### コンストラクタ

- コンストラクタの呼び出し時にすべての処理を行ってしまっているのが改善されてません

### requestメソッド

- `request`という名前のメソッドから推測される責務は「リクエストを送る」ですが、実体は「リクエストをパースしてファイルを読み込んでレスポンスを書き込む」というものです。そもそもメソッドの責務が多すぎるし、名前と一致してません
- 例外処理をロジックとして使うのをやめましょう。Methodのチェックやバージョンのチェックはif文でいいはずです

### filrCheckメソッド

- 名前が変ですね

## Error/BadRequest,MethodNotAllowed/VersionNotSupported

- パッケージ名に大文字を使ってるのはおかしいですね

## HttpRequest.java

こういう「根源となる例外を握りつぶして新しい例外を投げる」のはよくないです

```
        catch (IOException e) {
            throw new RuntimeException("BufferedReader読み込みに不具合がありました。");
        }
```

RuntimeExceptionのコンストラクタの第2引数に`cause`を渡しましょう

- メソッドのコメントは1つ上の行に書くよう統一しましょう

```
public String getVersion() {            //priavteのバージョンにアクセス
```

## FileResources.java

```

    public String getContentType() {

        if (url != null && !"".equals(url)) {
            for (String type : fileType.keySet()) {
                if (url.endsWith(type)) {
                    contentType = type;
                    break;
                }

            }
        }

        return fileType.getOrDefault(contentType, "Content-Type: text/html; charset=utf-8\n");
    }
```

このコードについて

- `type` ではなく `extension`では？
- `contentType`に代入されるものがContent-Typeではない
- 何のために`contentType`フィールドが存在する？

## HttpResponse.java

### makeStastusLine
- 名前
- `make`という名前のメソッドに期待されるのは何かを作成して返すことです

### contentType
- メソッドの名前は動詞
- `contentType`という名前のメソッドがファイルリソースを読み込んでレスポンスを書き込んでいるのはおかしいと思いませんか？

**Comment by lacolaco** [comment]
## Server.java

だんだん良くなってきた

- `ConnectionHandler connectionHandler = null;` と宣言する意味は？`connectionHandler`のスコープはtry句の中だけでは？
- `NullPointerException` だけをcatchしている意味は？

## ConnectionHandler.java

- `fileCheck` の名前はファイルが存在するかどうかをチェックする意味ですが副作用としてfileResourcesに新しいインスタンスが代入されています。そして戻り値として返したfileResourcesを更にreadRequest内でfileResourcesに代入しています。整理しましょう。
- try-catch文のスコープが大きすぎるという話を最初のレビューでしています
- finally句でnew FileResources("")を代入する意味は？このオブジェクトは何を表すんですか？

## HttpRequest.java

- `parseRequestLine`と`parseRequestParameter`をメソッドに分けるのはいいですがそれをすべてConnectionHandlerから呼び出させるのはよくないです。ConnectionHandlerはただパースをしてほしいだけなので、パース用のpublicメソッドがひとつだけある状態がよいです。細かいメソッドはそのpublicメソッドから呼び出されるprivateメソッドであるべきでしょう
- `get1` とか `post3` とかいう無意味な名前をやめましょう

## FileResources.java

- 前回も言ったけどなぜ`extension`フィールドが必要？そのフィールドはどこでどう使われてる？変数のスコープは基本的に狭いほうが良いです

## HttpResponse.java

- `throw new NullPointerException("エラー:出力ストリートがnullになっています");` ストリート？
- `selectContentType` select? 何を選んでいる？
- `レスポンセの書き込み` レスポンセ？
- `createResponse` create? 書き込んでいるだけでは？

## StatusLineTest.java

- これはStatusLineのテストのはずなのに、テストしているのがエラーメッセージのBodyというのはおかしいと思いませんか？そもそもStatusLineの責務がおかしいのでこうなっています

## ConnectionHandlerTest.java

- 何をテストしたいのかわからない テストケースには「〜〜のとき〜〜になる」という原因と結果を表現しましょう
- `new ConnectionHandler(is, os);` 何をしている？
- `リクエストがヌールか` ヌール？

メインのコードの修正にテストが追いついていなさそうなので、テストもちゃんと走らせながらメインのコードを直しましょう

**Comment by aziz819** [comment]
Server.java

だんだん良くなってきた

ConnectionHandler connectionHandler = null; と宣言する意味は？connectionHandlerのスコープはtry句の中だけでは？ →　特別な意味分からずにこう書きました。
NullPointerException だけをcatchしている意味は？ →　入出力ストリームがnullの場合にキャッチされる。
ConnectionHandler.java

fileCheck の名前はファイルが存在するかどうかをチェックする意味ですが副作用としてfileResourcesに新しいインスタンスが代入されています。→Fileクラスを継承しているんでコンストラクタに渡さないとないかどうかの確認できるか?
そして戻り値として返したfileResourcesを更にreadRequest内でfileResourcesに代入しています。整理しましょう。→　？？？　一つのメソッド内でインスタンス生成したり、違うメソッドを呼び出したりしないほうが良いということ？
try-catch文のスコープが大きすぎるという話を最初のレビューでしています　→　大きすぎるとは？？？リクエスト不具合時の不具合のキャッチとファイル見つからない時のキャッチしかないですけ
finally句でnew FileResources("")を代入する意味は？このオブジェクトは何を表すんですか？ →　だいぶ前の時につとように使ってた。
HttpRequest.java

parseRequestLineとparseRequestParameterをメソッドに分けるのはいいですがそれをすべてConnectionHandlerから呼び出させるのはよくないです。ConnectionHandlerはただパースをしてほしいだけなので、パース用のpublicメソッドがひとつだけある状態がよいです。細かいメソッドはそのpublicメソッドから呼び出されるprivateメソッドであるべきでしょう →　意味よく分からない ! ! !
get1 とか post3 とかいう無意味な名前をやめましょう　→　あとで変更
FileResources.java

前回も言ったけどなぜextensionフィールドが必要？そのフィールドはどこでどう使われてる？変数のスコープは基本的に狭いほうが良いです →　フィールドのスコープが広いから必要？どこで使われている？という問題が生まれた？ファイル拡張子によってContentTypeをセットしている & 変数のスコープを狭くした。
HttpResponse.java

throw new NullPointerException("エラー:出力ストリートがnullになっています"); ストリート？
selectContentType select? 何を選んでいる？ →　メソッド名前が変かもしれないけど、creatontentTypeに変更した
レスポンセの書き込み レスポンセ？
createResponse create? 書き込んでいるだけでは？ →　変なメソッド名なので、toWriteResponse に変更
StatusLineTest.java

これはStatusLineのテストのはずなのに、テストしているのがエラーメッセージのBodyというのはおかしいと思いませんか？そもそもStatusLineの責務がおかしいのでこうなっています
ConnectionHandlerTest.java

何をテストしたいのかわからない テストケースには「〜〜のとき〜〜になる」という原因と結果を表現しましょう
new ConnectionHandler(is, os); 何をしている？
リクエストがヌールか ヌール？
メインのコードの修正にテストが追いついていなさそうなので、テストもちゃんと走らせながらメインのコードを直しましょう

**Comment by lacolaco** [comment]
## Server.java

- 以前指摘した内容が修正されていません `ConnectionHandler connectionHandler = null;` と宣言する意味は？connectionHandlerのスコープはtry句の中だけでは？

## ConnectionHandler.java

- `getFilePas` 正しい英語を使いましょう
- `getFilePas` は名前と仕事が一致していません 何故ファイルパスを返すという名前のメソッドが何も返さずに`fileResources`に代入している？前回の指摘内容が解決してません
- `fileCheck` は `checkFile` が良いですね メソッドは動詞形です
- `fileCheck` にurlを渡している意味は？

## HttpRequest.java

- `parseRequest` メソッドが長すぎます。RequestLineやヘッダなどの部分ごとに別のメソッドに処理を分割しましょう
- `String[] urlSeparatorParameter`とか`String[] attributeSeparatorValue`とか、名前がおかしいですね。正しい英語を使いましょう。`SeparatorValue`と書かれるとセパレータの値にしか見えません

## HttpResponse.java

- `creatContentType` 正しい英語を使いましょう
- `String ContenType` 変数名をちゃんと書きましょう
- `toWriteResponse` というメソッド名は変です。動詞形で。`writeResponse`ならまだわかります

## FileResourcesTest.java

- 想定外の拡張子のファイルパスに対するテストを書きましょう

----

全体的に少し雑なコードに感じます。特に誤字脱字は自分でチェックできるものなのでレビューで指摘されないように気をつけましょう

**Comment by lacolaco** [comment]
- コードフォーマットを行いましょう
- 空白行が多すぎて読みにくいです

## Server.java

- `connectionHandler.createResponse();` createという名前から想定されるのは何かを作って返すだけの仕事ですが、このメソッドの仕事はレスポンスを作って、それをOutputStreamに書き込むことなので、名前と責務がズレてますね
- `readRequest()`と`createResponse()`を連続して呼び出していますが、これらは別々に呼び出す意味はないと思います。Serverから呼び出すのは単独のメソッドでよいのでは？

## ConnectionHandler.java

### `readRequest`メソッド

- try-catchしてますが、そもそもisがnullじゃないことはこのクラスのコンストラクタでチェックしているんだからここで例外は起きないんじゃないですか？
- 何かしらの例外が発生してstatusCodeがBad Requestに設定された後もmethodやurlなどの取得が続けられているけど、パースに失敗しているんだからこの処理はやっちゃいけないですね？
- メソッドのチェックとHTTPバージョンのチェックはファイルチェックの前にできるんじゃないですか？どんなメソッドでも必ずファイルの存在確認が先に行われるのはあまりよくない

### `createResponse`メソッド

- `readRequest`と同じですが、そもそもnullチェックをしてから処理を行えばNullPointerExceptionをわざわざ例外キャッチする必要ないですよね。if文によるnullチェックとその場合分けをちゃんとやりましょう

## HttpRequest.java

### parseRequestLineメソッド

- このメソッドがInputStreamを読み出してBufferedReaderを組み立てるのは名前と仕事が一致してないですね。parseRequestLineが呼び出される前にbufferedReaderは使用可能になっているべきでは？

## FileResource.java

- ContentTypeが改行コードまで含んで保持されているのはこのクラスの使用者にとって親切じゃない。普通はContentTypeを要求したらContentTypeだけが返ってくることを想像する。改行して使うかどうかはContentTypeを取得した側の都合ですね

## HttpResponse.java

- 誤字が直りませんね `contenType`
- createContentTypeメソッドはContentTypeを取得して、それをレスポンスに追記しているけどContentTypeの末尾にも改行がついてるしここでも改行すると2重に改行されるのでは？
